In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("Automobile_data1.csv")

In [4]:
df

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.4,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.4,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [5]:
import numpy as np

In [6]:
df=df.replace("?",np.nan)

In [7]:
print(df.head())

   symboling normalized-losses         make fuel-type aspiration num-of-doors  \
0          3               NaN  alfa-romero       gas        std          two
1          3               NaN  alfa-romero       gas        std          two
2          1               NaN  alfa-romero       gas        std          two
3          2               164         audi       gas        std         four
4          2               164         audi       gas        std         four

    body-style drive-wheels engine-location  wheel-base  ...  engine-size  \
0  convertible          rwd           front        88.6  ...          130
1  convertible          rwd           front        88.6  ...          130
2    hatchback          rwd           front        94.5  ...          152
3        sedan          fwd           front        99.8  ...          109
4        sedan          4wd           front        99.4  ...          136

   fuel-system  bore  stroke compression-ratio horsepower  peak-rpm city-mpg  \
0         mpfi  3.47    2.68               9.0        111      5000       21
1         mpfi  3.47    2.68               9.0        111      5000       21
2         mpfi  2.68    3.47               9.0        154      5000       19
3         mpfi  3.19     3.4              10.0        102      5500       24
4         mpfi  3.19     3.4               8.0        115      5500       18

  highway-mpg  price
0          27  13495
1          27  16500
2          26  16500
3          30  13950
4          22  17450

[5 rows x 26 columns]

In [8]:
df.dtypes

symboling              int64
normalized-losses     object
make                  object
fuel-type             object
aspiration            object
num-of-doors          object
body-style            object
drive-wheels          object
engine-location       object
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
engine-type           object
num-of-cylinders      object
engine-size            int64
fuel-system           object
bore                  object
stroke                object
compression-ratio    float64
horsepower            object
peak-rpm              object
city-mpg               int64
highway-mpg            int64
price                 object
dtype: object

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    int64
 1   normalized-losses  164 non-null    object
 2   make               205 non-null    object
 3   fuel-type          205 non-null    object
 4   aspiration         205 non-null    object
 5   num-of-doors       203 non-null    object
 6   body-style         205 non-null    object
 7   drive-wheels       205 non-null    object
 8   engine-location    205 non-null    object
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64
 14  engine-type        205 non-null    object
 15  num-of-cylinders   205 non-null    object
 16  engine-size        205 non-null    int64
 17  fuel-system        205 non-null    object
 18  bore               201 non-null    object
 19  stroke             201 non-null    object
 20  compression-ratio  205 non-null    float64
 21  horsepower         203 non-null    object
 22  peak-rpm           203 non-null    object
 23  city-mpg           205 non-null    int64
 24  highway-mpg        205 non-null    int64
 25  price              201 non-null    object
dtypes: float64(5), int64(5), object(16)
memory usage: 41.8+ KB

In [10]:
numeric_columns=["horsepower","peak-rpm","price","bore","stroke"]

In [11]:
for col in numeric_columns:
    df[col]=pd.to_numeric(df[col],errors="coerce")
print(df[col].dtypes)

float64

In [12]:
df[['horsepower','peak-rpm','price','bore','stroke']].isnull()

     horsepower  peak-rpm  price   bore  stroke
0         False     False  False  False   False
1         False     False  False  False   False
2         False     False  False  False   False
3         False     False  False  False   False
4         False     False  False  False   False
..          ...       ...    ...    ...     ...
200       False     False  False  False   False
201       False     False  False  False   False
202       False     False  False  False   False
203       False     False  False  False   False
204       False     False  False  False   False

[205 rows x 5 columns]

In [13]:
df["bore"]=df["bore"].fillna(df["bore"].median())

In [14]:
df["stroke"]=df["stroke"].fillna(df["stroke"].median())

In [15]:
df["horsepower"]=df["horsepower"].fillna(df["horsepower"].median())

In [16]:
df["peak-rpm"]=df["peak-rpm"].fillna(df["peak-rpm"].median())

In [17]:
df["price"]=df["price"].fillna(df["price"].median())

In [18]:
df["power_to_weight_ratio"]=df["horsepower"]/df["curb-weight"]
print(df[["horsepower","curb-weight","power_to_weight_ratio"]].head())

   horsepower  curb-weight  power_to_weight_ratio
0       111.0         2548               0.043564
1       111.0         2548               0.043564
2       154.0         2823               0.054552
3       102.0         2337               0.043646
4       115.0         2824               0.040722

In [20]:
df["combined_mpg"]=(df["city-mpg"]+df["highway-mpg"])/2
print(df[["city-mpg","highway-mpg","combined_mpg"]].head())

   city-mpg  highway-mpg  combined_mpg
0        21           27          24.0
1        21           27          24.0
2        19           26          22.5
3        24           30          27.0
4        18           22          20.0

In [22]:
body_style_summary=df.groupby("body-style")[
    ["price","horsepower","curb-weight","combined_mpg","power_to_weight_ratio"]
].agg(["count","mean","median","max"])
print(body_style_summary)

            price                                 horsepower              \
            count          mean   median      max      count        mean
body-style
convertible     6  21890.500000  17084.5  37028.0          6  131.666667
hardtop         8  22208.500000  19687.5  45400.0          8  142.250000
hatchback      70   9967.085714   8897.0  22018.0         70  101.242857
sedan          96  14372.989583  10846.5  41315.0         96  103.104167
wagon          25  12371.960000  11694.0  28248.0         25   97.640000

                          curb-weight                            combined_mpg  \
            median    max       count         mean  median   max        count
body-style
convertible  113.5  207.0           6  2801.666667  2674.0  3685            6
hardtop      119.5  207.0           8  2810.625000  2717.5  3715            8
hatchback     89.0  288.0          70  2348.185714  2294.5  3366           70
sedan         96.0  262.0          96  2610.593750  2410.0  4066           96
wagon         95.0  162.0          25  2784.240000  2650.0  3750           25

                                    power_to_weight_ratio                      \
                  mean median   max                 count      mean    median
body-style
convertible  23.250000  24.00  27.0                     6  0.047006  0.042813
hardtop      24.437500  25.25  34.0                     8  0.050502  0.045705
hatchback    29.242857  28.75  51.5                    70  0.041773  0.038540
sedan        28.078125  27.75  47.5                    96  0.038861  0.037961
wagon        26.380000  26.00  34.0                    25  0.035045  0.034714


                  max
body-style
convertible  0.073929
hardtop      0.075109
hatchback    0.085561
sedan        0.066329
wagon        0.051315

In [25]:
engine_location_summary=df.groupby("engine-location")[
    ["price","horsepower","curb-weight","combined_mpg","power_to_weight_ratio"]
].agg(["count","mean","median","max"])
print(engine_location_summary)

                price                                 horsepower              \
                count          mean   median      max      count        mean
engine-location
front             202  12832.816832  10295.0  45400.0        202  102.638614
rear                3  34528.000000  34028.0  37028.0          3  207.000000

                              curb-weight                             \
                median    max       count         mean  median   max
engine-location
front             95.0  288.0         202  2552.371287  2412.0  4066
rear             207.0  207.0           3  2770.666667  2756.0  2800

                combined_mpg                         power_to_weight_ratio  \
                       count       mean median   max                 count
engine-location
front                    202  28.089109   27.0  51.5                   202
rear                       3  21.000000   21.0  21.0                     3


                     mean    median       max
engine-location
front            0.039568  0.037687  0.085561
rear             0.074715  0.075109  0.075109